"""Surface-language feature inventory for question intent routing.

These constants describe reusable linguistic cues used by the rule-based
router. They are intentionally dataset-agnostic: no dataset names, sample ids,
gold answers, or judge outputs are represented here.
"""

from __future__ import annotations


WHAT_ENUMERABLE_ENTITY_HEADS = (
    "books",
    "activities",
    "items",
    "people",
    "shelters",
    "states",
    "countries",
    "european countries",
    "authors",
    "pets",
    "damages",
    "subjects",
    "kind of interests",
)
WHICH_LOCATION_ENTITY_HEADS = (
    "countries",
    "european countries",
    "us cities",
    "u.s. cities",
    "city",
    "cities",
    "geographical locations",
)

ASSISTANT_MEMORY_REFERENCE_CUES = (
    "previous chat",
    "previous conversation",
    "previously discussed",
    "looking back",
    "trying to recall",
    "we discussed",
    "we talked about",
    "talked about last time",
    "last time",
    "do you remember",
    "remind me",
    "you suggested",
    "you said",
    "you told",
    "you mentioned",
    "you provided",
    "you gave",
    "you recommended",
    "you outlined",
    "you created",
    "you wrote",
    "you called",
    "you advised",
    "what did you say",
    "what did you tell",
    "what did you suggest",
    "what did you recommend",
    "what advice did you",
    "your suggestion",
    "your recommendation",
)

ADVICE_REQUEST_CUES = (
    "recommend",
    "suggest",
    "advice",
    "any tips",
    "what do you think",
    "should i",
    "would it be a good idea",
    "help me decide",
    "which should i",
    "what should i",
    "do you think it",
)
GENERIC_ADVICE_REQUEST_CUES = (
    "recommend",
    "suggest",
    "advice",
    "tips",
    "should i",
    "would it be a good idea",
    "help me decide",
    "which should i",
    "what should i",
)
SET_OPERATION_ADVICE_EXCLUSION_CUES = (
    "recommend",
    "suggest",
    "advice",
    "appropriate",
    "good gift",
    "gift for",
    "would be a good",
    "what should",
    "which should",
)
PERSONALIZED_INFERENCE_PHRASES = (
    "benefit from",
    "good fit",
    "be good for",
    "would enjoy",
    "might enjoy",
    "likely enjoy",
    "would like",
    "might like",
    "likely like",
    "might consider",
    "could consider",
    "alternative career",
    "underlying condition",
)

AGGREGATION_CUES = (
    "how many",
    "how much",
    "total",
    "in total",
    "combined",
    "average",
    "percentage",
    "difference",
    "more than",
    "less than",
    "spent",
    "cost",
    "count",
    "sum",
)
AGGREGATION_PHRASES = (
    "how many",
    "how much",
    "in total",
    "combined",
    "average",
    "percentage",
    "difference",
    "more than",
    "less than",
)
AGGREGATION_TERMS = ("total", "spent", "cost", "costs", "count", "counts", "sum")

ENUMERABLE_HEAD_STOPWORDS = {
    "what",
    "which",
    "are",
    "were",
    "is",
    "was",
    "do",
    "does",
    "did",
    "has",
    "have",
    "had",
    "the",
    "a",
    "an",
    "of",
    "my",
    "your",
}
PLURAL_HEAD_STOPWORDS = {
    "what",
    "which",
    "are",
    "were",
    "is",
    "was",
    "do",
    "did",
    "does",
    "have",
    "has",
    "the",
    "a",
    "an",
    "my",
    "i",
    "we",
    "you",
    "first",
    "last",
    "latest",
    "current",
    "previous",
    "initial",
    "original",
    "date",
    "time",
    "year",
    "month",
    "day",
}
IRREGULAR_ENUMERABLE_HEADS = {"people", "children", "kids"}

MEMORY_EVENT_PREDICATES = (
    "read",
    "visit",
    "visited",
    "been to",
    "buy",
    "bought",
    "made",
    "done",
    "partake",
    "participated",
    "attended",
    "met",
    "helped",
    "mention",
    "mentioned",
    "volunteer",
    "vacationed",
    "collect",
    "collected",
    "enjoy",
    "have",
    "has",
    "own",
    "owns",
    "adopted",
    "recommend",
    "recommended",
    "use",
    "uses",
    "used",
    "watch",
    "watched",
    "seen",
    "travel",
    "traveled",
    "travelled",
    "pursue",
    "pursued",
    "happened",
)

NON_ENUMERABLE_SURFACE_CUES = (
    "would",
    "wouldn't",
    "would not",
    "might",
    "likely",
    "relationship status",
    "what are some ",
    "what personality traits",
    "what kind of",
    "what type of",
    "which type of",
    "what are the skills",
    "what similar",
    "what things",
    "what causes",
    "what areas",
)
NON_ENUMERABLE_STYLE_CUES = (
    "total number",
    "what style",
    "what styles",
    "what kind of style",
    "which style",
    "which styles",
)
DESCRIPTIVE_QUESTION_HEADS = (
    "what emotions",
    "what feelings",
    "what attributes",
    "what traits",
    "what qualities",
    "what characteristics",
    "what habits",
    "what dreams",
    "what goals",
    "what challenges",
    "what difficulties",
    "what problems",
    "what ways",
    "what methods",
    "what reasons",
    "what thoughts",
    "what opinions",
    "what memories",
    "what progress",
    "what focus",
    "what kind of dream",
)
DESCRIPTIVE_QUESTION_PATTERNS = (
    r"\bwhat\b.*\b(?:represent|describe|mean|symbolize)\b",
    r"\bwhat\b.*\b(?:motivat(?:e|es|ed|ing)|inspir(?:e|es|ed|ing))\b",
    r"\bwhat\b.*\b(?:think|feel|say)\b.*\babout\b",
    r"\bwhat\b.*\b(?:recommend|recommended|recommendations?|suggest|suggested|suggestions?|advice|tips)\b",
    r"\bwhat\b.*\b(?:use|uses|used)\b.*\bfor\b",
)

TEMPORAL_SURFACE_CUES = (
    "when",
    "what date",
    "what time",
    "how long",
    "duration",
    "since",
    "before",
    "after",
    "earlier",
    "later",
    "first",
    "chronological",
    "earliest",
    "latest",
)
GENERIC_RECENCY_CUES = (
    "current",
    "currently",
    "now",
    "latest",
    "most recent",
    "recently",
    "previous",
    "initial",
    "original",
    "used to",
)
TEMPORAL_RETRIEVAL_CUES = (
    "when",
    "what date",
    "which happened first",
    "what happened first",
    "happened first",
    "occurred first",
    "meet first",
    "met first",
    "order of",
    "from earliest",
    "earliest to latest",
    "chronological",
    "ago",
    "before",
    "after",
    "earlier",
    "later",
    "how long",
    "duration",
    "since",
    "last month",
    "past month",
    "past two weeks",
    "this year",
)
STRICT_TEMPORAL_CUES = (
    "when",
    "what date",
    "what time",
    "how long",
    "how old",
    "order of",
    "from earliest",
    "earliest to latest",
    "chronological",
    "which happened first",
    "what happened first",
    "happened first",
    "occurred first",
    "meet first",
    "met first",
    "first issue",
    "last month",
    "past month",
)
STRICT_TEMPORAL_PATTERNS = (
    r"\bprevious\b.*\b(?:frequent flyer|goal|plan|status|membership|program)\b",
    r"\bbefore\b.*\b(?:started|today)\b",
    r"\bmove\s+(?:i|you|we|they)\s+made\s+after\b",
    r"\bperiod\b.*\bafter\b",
)
RECENCY_STATE_CUES = (
    "current",
    "currently",
    "now",
    "latest",
    "most recent",
    "recent",
    "previous",
    "previously",
    "initial",
    "initially",
    "original",
    "usually",
    "used to",
)
ORDERING_CUES = (
    "order of",
    "from earliest to latest",
    "earliest to latest",
    "chronological",
    "which happened first",
    "what happened first",
    "happened first",
    "occurred first",
    "meet first",
    "met first",
    "purchase first",
    "purchased first",
    "buy first",
    "bought first",
    "first,",
)
DURATION_CUES = (
    "how many days",
    "how many weeks",
    "how many months",
    "how long",
    "days ago",
    "weeks ago",
    "months ago",
    "since",
)
HISTORICAL_STATE_CUES = ("previous", "initial", "initially", "original", "used to", "usually")
TEMPORAL_QUANTITY_CUES = ("how many", "how much", "difference", "compared")
TEMPORAL_ORDER_CUES = ("earlier", "later", "before", "after")
RECURRING_SCOPE_EXCLUSION_CUES = ("how many", "how much", "total", "average", "sum", "combined", "difference")
STRICT_MULTI_AGGREGATION_PATTERNS = (
    r"\bhow many\b.*\b(?:replace|fix|replaced|fixed)\b",
    r"\byears? older\b",
    r"\bhow much older\b",
    r"\b(?:total number of|how many)\s+siblings\b",
)
BROAD_ENUMERABLE_CONTEXT_PATTERNS = (
    r"\b(which|what)\s+(?:u\.?s\.?\s+)?cit(?:y|ies)\b",
    r"\b(which|what)\s+(?:european\s+)?countr(?:y|ies)\b",
    r"\b(which|what)\s+geographical\s+locations\b",
    r"\bwhat subjects?\b.*\bboth\b",
    r"\bwhat do\b.*\bboth have in common\b",
)
TEMPORALLY_SCOPED_ENUMERABLE_CONTEXT_PATTERNS = (
    r"\b(which|what)\s+(?:u\.?s\.?\s+)?cities\b",
    r"\b(which|what)\s+(?:european\s+)?countries\b",
    r"\b(which|what)\s+geographical\s+locations\b",
    r"\bwhat subjects?\b.*\bboth\b",
    r"\bwhat do\b.*\bboth have in common\b",
)
EVENT_ENUMERABLE_CONTEXT_PATTERNS = (
    r"\bwhat items?\b.*\b(buy|bought|purchase|purchased)\b",
)
RERANK_FACTUAL_SLOT_EXCLUSION_CUES = (
    "what are ",
    "what were ",
    "what kind of ",
    "what kinds of ",
    "what type of ",
    "what types of ",
    "what style of ",
    "what places ",
    "what things ",
    "what items ",
    "what activities ",
    "what events ",
    "what books ",
    "what games ",
    "what bands ",
    "what artists",
    "what symbols ",
    "who have ",
    "who or which ",
    "which places ",
    "which bands ",
    "which of ",
    "shared ",
    "similar ",
    "likely ",
    "might ",
    "could ",
    "would ",
    "besides ",
    "other than ",
    "how often ",
    "how did ",
    "how many ",
    "how long ",
    "what can ",
)

MONTH_NAMES = (
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
)
